Update patch set 1
Patch Set 1: Code-Review-1

(9 comments)

Thanks for the patch, this sounds great!

First, I am nearly sure you do not execute the script install_hooks.sh, which put a signed-off-by tag in the commit message and execute the checkpatch script, to check the patch format. The result of the script is described below.

Second, maybe we can start splitting the store.c file, and putting the alias-feature functions in a store_alias.c. Patrice and Thomas can tell if they agree or not.

Finally, I ran the checkpatch script (35 comments) and the test suite: the acceptance.sh failed. I put the outputs below.

--------------------

ERROR: trailing whitespace        
#9: FILE: src/cli/phobos/cli.py:297:       
+        parser.add_argument('-a', '--alias', $
                                                       
WARNING: line over 80 characters  
#67: FILE: src/include/phobos_store.h:69:       
+    const char      *alias;       /**< Identifier for family, layout, tag combination */
                                 
ERROR: "foo * bar" should be "foo *bar"  
#105: FILE: src/store/store.c:214:
+    (char * section_name, char * config_param, const char ** res)
                                  
ERROR: "foo * bar" should be "foo *bar"
#105: FILE: src/store/store.c:214:
+    (char * section_name, char * config_param, const char ** res)
                                                       
ERROR: "foo ** bar" should be "foo **bar"
#105: FILE: src/store/store.c:214:
+    (char * section_name, char * config_param, const char ** res)
      
ERROR: "foo * bar" should be "foo *bar"
#109: FILE: src/store/store.c:217:
+    const char * res_dup = *res;

ERROR: that open brace { should be on the previous line
#115: FILE: src/store/store.c:220:
+    if (rc)
+    {

ERROR: space required before the open parenthesis '('
#140: FILE: src/store/store.c:244:
+    if(tag_str == NULL || tags == NULL)

WARNING: Missing a blank line after declarations
#151: FILE: src/store/store.c:255:
+    size_t n_alias_tags = 0;
+    while(single_tag != NULL)

ERROR: that open brace { should be on the previous line
#151: FILE: src/store/store.c:255:
+    while(single_tag != NULL)
+    {

ERROR: space required before the open parenthesis '('
#151: FILE: src/store/store.c:255:
+    while(single_tag != NULL)

ERROR: that open brace { should be on the previous line
#159: FILE: src/store/store.c:263:
+    if (tags->n_tags > 0)
+    {

ERROR: trailing whitespace
#161: FILE: src/store/store.c:265:
+        tags->tags = realloc(tags->tags, $

ERROR: that open brace { should be on the previous line
#164: FILE: src/store/store.c:268:
+    else
+    {

ERROR: else should follow close brace '}'
#164: FILE: src/store/store.c:268:
+    }
+    else

ERROR: trailing whitespace
#168: FILE: src/store/store.c:272:
+        $

ERROR: trailing whitespace
#173: FILE: src/store/store.c:277:
+    $

WARNING: Missing a blank line after declarations
#175: FILE: src/store/store.c:279:
+    size_t i = tags->n_tags;
+    for (single_tag = strtok_r(parse_tag_str, ",", &saveptr2);

ERROR: that open brace { should be on the previous line
#175: FILE: src/store/store.c:279:
+    for (single_tag = strtok_r(parse_tag_str, ",", &saveptr2);
+         single_tag != NULL;
+         single_tag = strtok_r(NULL, ",", &saveptr2), i++)
+    {

ERROR: trailing whitespace
#191: FILE: src/store/store.c:295:
+ * If an alias is given, the corresponding values are loaded and added if $

ERROR: trailing whitespace
#207: FILE: src/store/store.c:311:
+    $

ERROR: that open brace { should be on the previous line
#213: FILE: src/store/store.c:317:
+    if (xfer->xd_params.put.alias != NULL)
+    {

ERROR: "foo* bar" should be "foo *bar"
#215: FILE: src/store/store.c:319:
+        char* section_name;

WARNING: line over 80 characters
#217: FILE: src/store/store.c:321:
+        rc = asprintf(&section_name, ALIAS_SECTION_CFG, xfer->xd_params.put.alias);

ERROR: "foo * bar" should be "foo *bar"
#230: FILE: src/store/store.c:334:
+        const char * alias_tags;

WARNING: Missing a blank line after declarations
#231: FILE: src/store/store.c:335:
+        const char * alias_tags;
+        alias_val_from_cfg

ERROR: that open brace { should be on the previous line
#235: FILE: src/store/store.c:339:
+        if (alias_tags != NULL)
+        {

ERROR: that open brace { should be on the previous line
#238: FILE: src/store/store.c:342:
+            if (rc)
+            {

WARNING: line over 80 characters
#240: FILE: src/store/store.c:344:
+                pho_error(rc, "Unable to load tags from \"%s\" tag string \"%s\"",

ERROR: trailing whitespace
#248: FILE: src/store/store.c:352:
+    /* $

ERROR: trailing whitespace
#249: FILE: src/store/store.c:353:
+     * fill alias or default values into put params if not set prelimilarly $

ERROR: trailing whitespace
#253: FILE: src/store/store.c:357:
+    if(xfer->xd_params.put.family == PHO_RSC_INVAL || $

ERROR: space required before the open parenthesis '('
#253: FILE: src/store/store.c:357:
+    if(xfer->xd_params.put.family == PHO_RSC_INVAL ||

ERROR: space required before the open parenthesis '('
#257: FILE: src/store/store.c:361:
+    if(xfer->xd_params.put.layout_name == NULL)

ERROR: trailing whitespace
#259: FILE: src/store/store.c:363:
+    $

ERROR: trailing whitespace
#274: FILE: src/store/store.c:945:
+    $

ERROR: trailing whitespace
#287: FILE: src/store/store.c:952:
+        $

ERROR: trailing whitespace
#337: FILE: src/tests/acceptance.sh:341:
+    $PSQL -t -c "$fam_request1" | $

ERROR: trailing whitespace
#339: FILE: src/tests/acceptance.sh:343:
+        error "Put with non-existant alias should have written object on a $

ERROR: trailing whitespace
#342: FILE: src/tests/acceptance.sh:346:
+    $PSQL -t -c "$fam_request2" | $

ERROR: trailing whitespace
#344: FILE: src/tests/acceptance.sh:348:
+        error "Put with non-existant alias should have written object on a $

total: 35 errors, 6 warnings, 343 lines checked

--------------------

=============================================
   phobos 1.90.0: src/tests/test-suite.log
=============================================

# TOTAL: 20
# PASS:  19
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

FAIL: acceptance
================
...
+ put_alias acceptance-test
+ local 'PSQL=psql phobos phobos'
+ local id1=test/hosts-alias1.27374
+ local id2=test/hosts-alias2.27374
+ local 'lay_request1=SELECT lyt_info FROM extent WHERE oid='\''test/hosts-alias1.27374'\'';'
+ local 'lay_request2=SELECT lyt_info FROM extent WHERE oid='\''test/hosts-alias2.27374'\'';'
+ local 'fam_request1=SELECT extents FROM extent WHERE oid='\''test/hosts-alias1.27374'\'';'
+ local 'fam_request2=SELECT extents FROM extent WHERE oid='\''test/hosts-alias2.27374'\'';'
+ local alias_good=acceptance-test
+ local alias_bad=alias-noexist
+ /home/gougeauds/phobos/src/cli/scripts/phobos put -a alias-noexist /etc/hosts test/hosts-alias1.27374
2020-11-06 08:54:00,330 <INFO> Unable to find parameter 'family' in section 'alias "alias-noexist"' of the configuration
2020-11-06 08:54:00,330 <INFO> Unable to find parameter 'layout' in section 'alias "alias-noexist"' of the configuration
2020-11-06 08:54:00,330 <INFO> Unable to find parameter 'tags' in section 'alias "alias-noexist"' of the configuration
2020-11-06 08:54:00,345 <INFO> PUT operation for objid:'test/hosts-alias1.27374' succeeded
+ /home/gougeauds/phobos/src/cli/scripts/phobos put -a acceptance-test /etc/hosts test/hosts-alias2.27374
2020-11-06 08:54:00.481874000 <INFO> Media '/tmp/test.pho.1' is locked (vm0:00006b2b:000000005fa50f25:0000000000000000)
2020-11-06 08:54:00.482514000 <WARNING> Available space on media : 0, required size : 97158
2020-11-06 08:54:00,484 <ERROR> Encoder for objid:'test/hosts-alias2.27374' received error write alloc to last request: No space left on device
2020-11-06 08:54:00,484 <INFO> PUT operation for objid:'test/hosts-alias2.27374' failed
2020-11-06 08:54:00,487 <ERROR> Cannot PUT '/etc/hosts' to 'objid:test/hosts-alias2.27374': Cannot store objects: No space left on device
+ error 'Put with existing alias should have worked'
+ echo 'Put with existing alias should have worked'
Put with existing alias should have worked
+ waive_daemon
+ kill 27435
+ tail --pid=27435 -f /dev/null
2020-11-06 08:54:00.494334000 <ERROR> Socket poll probe failed: Interrupted system call (4)
2020-11-06 08:54:00.494378000 <ERROR> Error during request reception: Interrupted system call (4)
+ wait
+ exit 1
+ cleanup
+ waive_daemon
+ kill 27435
+ echo 'Daemon was not running'
Daemon was not running
+ tail --pid=27435 -f /dev/null
+ rm -rf /tmp/test.pho.1 /tmp/test.pho.2 /tmp/tmp.Ky99UcM0eK

Patch-set: 1
Reviewer: Gerrit User 1017196 <1017196@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=-1