fix: cli logger error if errno does not exist
If an error occured and the errno does not exist, an exception is raised
because abs() does not accept NoneType. In this case, we just print a
null string.

Traceback (most recent call last):
  File "/bin/phobos", line 30, in <module>
    phobos_main()
  File "/usr/lib64/python3.6/site-packages/phobos/cli.py", line 1575, in
phobos_main
    PhobosActionContext(args if args is not None else
sys.argv[1::]).run()
  File "/usr/lib64/python3.6/site-packages/phobos/cli.py", line 1563, in
run
    getattr(target_inst, 'exec_%s' % action.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/phobos/cli.py", line 885, in
exec_list
    self.logger.error("Cannot list objects: %s", env_error_format(err))
  File "/usr/lib64/python3.6/site-packages/phobos/cli.py", line 96, in
env_error_format
    return "%s: %s" % (exc.strerror, os.strerror(abs(exc.errno)))
TypeError: bad operand type for abs(): 'NoneType'

Change-Id: Iab629c124801e28fe06a653a5e5b5b7547e3a929
Signed-off-by: Sebastien Gougeaud <sebastien.gougeaud@cea.fr>
Reviewed-on: https://gerrit.ccc.ocre.cea.fr/gerrit/c/phobos/+/8295
Tested-by: Jenkins s8open_nr <s8open_nr@ccc.ocre.cea.fr>
Reviewed-by: Yoann VALERI <yoann.valeri@cea.fr>
Reviewed-by: Patrice LUCAS <patrice.lucas@cea.fr>